# Generated by Django 3.1.7 on 2021-03-31 02:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForumServe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(blank=True, max_length=100, null=True)),
                ('blog_content', models.CharField(blank=True, max_length=10000, null=True)),
                ('blogger_id', models.IntegerField()),
                ('release_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
