# Generated by Django 3.1.7 on 2021-03-31 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ForumServe', '0002_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blogger_id',
        ),
    ]
