# Generated by Django 3.1.7 on 2021-03-31 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForumServe', '0003_remove_blog_blogger_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
