# Generated by Django 3.1.7 on 2021-03-31 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForumServe', '0004_blog_blog_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_content',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
    ]
