# Generated by Django 3.1.7 on 2021-03-31 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForumServe', '0005_auto_20210331_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_id', models.CharField(max_length=1000)),
                ('blog_reviewer', models.CharField(max_length=1000)),
                ('comment', models.CharField(max_length=1000)),
            ],
        ),
    ]
