# Generated by Django 3.1.7 on 2021-03-31 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForumServe', '0006_blogmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forum_title', models.CharField(blank=True, max_length=100, null=True)),
                ('forum_name', models.CharField(blank=True, max_length=100)),
                ('release_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='ForumMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forum_id', models.CharField(max_length=1000)),
                ('forum_reviewer', models.CharField(max_length=1000)),
                ('forum_comment', models.CharField(max_length=1000)),
            ],
        ),
    ]
