# Generated by Django 3.1.7 on 2021-04-01 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForumServe', '0007_forum_forummessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(blank=True, max_length=100)),
                ('question_content', models.CharField(blank=True, max_length=100000, null=True)),
                ('question_name', models.CharField(blank=True, max_length=100)),
                ('question_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
